fix: Solve SRF issues
The following example threw the error.

```
CREATE (:v)-[:e]->(:v);
MATCH p=()-[]->() RETURN unnest(nodes(p));
ERROR:  set-valued function called in context that cannot accept a set
```

And now it works.

(cherry picked from commit a8f206db8791d77f9784e7573ebfde60d121df80)